spring.application.name=ticket
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_app
spring.datasource.username=yevheniibondarenko
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=une-cle-secrete-suffisamment-longue-et-aleatoire-a-ne-jamais-partager-publiquement
jwt.expiration=86400000

