server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        # renvoie tout appel /api/... vers le service backend (nom résolu par
        # le DNS interne Docker Compose ou Kubernetes selon l'environnement)
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        # renvoie index.html pour toute route inconnue de nginx (ex: /dashboard, /tickets)
        # pour laisser Angular gérer le routing côté client
        try_files $uri $uri/ /index.html;
    }
}
