server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # renvoie index.html pour toute route inconnue de nginx (ex: /dashboard, /tickets)
        # pour laisser Angular gérer le routing côté client
        try_files $uri $uri/ /index.html;
    }
}
